# Generated by Django 6.0.1 on 2026-01-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(default='noemail@local.com', max_length=254),
            preserve_default=False,
        ),
    ]
