# Generated by Django 6.0.1 on 2026-01-18 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='comentario',
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda.pedido'),
        ),
    ]
