# Generated by Django 6.0.1 on 2026-01-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_calificacion_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='comentario',
            field=models.TextField(blank=True),
        ),
    ]
