# Generated by Django 6.0.1 on 2026-01-18 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='pedido',
        ),
    ]
